import './account';
import './calendar';
import './chat';
import './customers';
import './invoices';
import './kanban';
import './mail';
import './notifications';
import './orders';
import './products';
import './project';
import './reports';
import './search';
import './userroles';
import './roles';
import './cmsusers';
import './companys';
import './module';
import './systemadministrators';
import './social';
import './soscontacts';
import './companies';
import './beneficios';
import './faqs';
import './noticias';
import './language';

// 2021.02.22
import './students';
import './constants'
import './lessons'
import './bills'
import './groups'
import './teacher'
import './textbook'
import './more'
// 2021.02.22
